# Docker Compose version is now optional in newer versions

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hospital
      MYSQL_USER: ${MYSQL_USER:-hospital_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-hospital_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # RabbitMQ (Optional - for message queuing)
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: hospital-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-hospital_user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-hospital_pass}
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10
    profiles:
      - messaging

  # Hospital Management Application
  hospital-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: hospital-management:latest
    container_name: hospital-app
    restart: unless-stopped
    environment:
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      # JPA configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

      # JWT configuration
      JWT_SECRET: mySecretKeyThatNeedsToBeAtLeast32Characters
      JWT_EXPIRATION: 1800000

      # RabbitMQ configuration (optional)
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-hospital_user}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-hospital_pass}

      # Application configuration
      SERVER_PORT: 8080
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_HOSPITAL_SYSTEM: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: hospital-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - hospital-app
    networks:
      - hospital-network
    profiles:
      - production

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  hospital-network:
    driver: bridge
